# Generated by Django 3.1 on 2020-11-08 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0002_auto_20201108_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('job', models.CharField(choices=[('0', 'Marketer'), ('1', 'Administrator'), ('2', 'HR Specialist'), ('3', 'Accountant'), ('4', 'Worker'), ('5', 'Salesman'), ('6', 'Other')], max_length=1, verbose_name='Job')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
            ],
        ),
    ]
