# Generated by Django 3.1 on 2020-11-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(editable=False, max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='department',
            name='tag',
            field=models.CharField(blank=True, max_length=15, unique=True, verbose_name='Tag'),
        ),
    ]
