# Generated by Django 3.1 on 2020-11-08 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_auto_20201108_0928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['-name'], 'verbose_name': 'Department', 'verbose_name_plural': 'Department'},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'tag')},
        ),
    ]
